-- Master ID Scripts
-- Database
USE WMS;

INSERT INTO tblverticalid (VERT_ID,LANG_ID,VERTICAL,REMARK,IS_DELETED,CTD_BY,CTD_ON,UTD_BY,UTD_ON)
VALUES (1,'EN','Retail','Remarks', 0,'SUPERADMIN',GETDATE(),'SUPERADMIN',GETDATE());
GO

INSERT INTO tblcompanyid (C_ID,LANG_ID,C_TEXT,IS_DELETED,CTD_BY,CTD_ON,UTD_BY,UTD_ON)
VALUES (1000,'EN','True Value',0,'SUPERADMIN',GETDATE(),'SUPERADMIN',GETDATE());
GO

INSERT INTO tblwarehouseid (C_ID,WH_ID,LANG_ID,PLANT_ID,WH_TEXT,IS_DELETED,CTD_BY,CTD_ON,UTD_BY,UTD_ON)
VALUES (1000,'110','EN',1001,'TV Warehouse',0,'SUPERADMIN',GETDATE(),'SUPERADMIN',GETDATE());
GO

INSERT INTO tblwarehouseid (C_ID,WH_ID,LANG_ID,PLANT_ID,WH_TEXT,IS_DELETED,CTD_BY,CTD_ON,UTD_BY,UTD_ON)
VALUES (1000,'111','EN',1001,'TE Warehouse',0,'SUPERADMIN',GETDATE(),'SUPERADMIN',GETDATE());
GO

INSERT INTO tblplantid (C_ID,PLANT_ID,LANG_ID,PLANT_TEXT,IS_DELETED,CTD_BY,CTD_ON,UTD_BY,UTD_ON)
VALUES (1000,1001,'EN','True Value',0,'SUPERADMIN',GETDATE(),'SUPERADMIN',GETDATE());
GO

INSERT INTO tblfloorid (C_ID,PLANT_ID,WH_ID,FL_ID,LANG_ID,FL_TEXT,IS_DELETED,CTD_BY,CTD_ON,UTD_BY,UTD_ON)
VALUES (1000,1001,'110','01','EN','Basement floor',0,'SUPERADMIN',GETDATE(),'SUPERADMIN',GETDATE());
GO