-- Master ID Scripts
-- Database
USE WMS;

-- LANGUAGE ID Table
CREATE TABLE `WMS`.`tbllanguageid` (
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `LANG_TEXT` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`LANG_ID`))
GO

-- Vertical ID Table
CREATE TABLE `WMS`.`tblverticalid` (
  `VERT_ID` INT NOT NULL,
  `LANG_ID` NVARCHAR(5) NOT NULL,
  `VERTICAL` NVARCHAR(50) NULL,
  `REMARK` NVARCHAR(500) NULL,
  `IS_DELETED` INT NULL,
  `CTD_BY` NVARCHAR(50) NULL,
  `CTD_ON` DATETIME NULL,
  `UTD_BY` NVARCHAR(50) NULL,
  `UTD_ON` DATETIME NULL,
  PRIMARY KEY (`VERT_ID`, `LANG_ID`))
GO