#remote
server.port=8787
server.servlet.context-path=/classicwms/api/wms-outboundtransaction-service

#UAT
#spring.datasource.url=jdbc:sqlserver://10.10.6.30;databaseName=WMS_WK
#spring.datasource.username=sa
#spring.datasource.password=SuHcHQR72nxvyJx6EPpoOsK4V
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=false
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:sqlserver://10.10.10.61;databaseName=WMS_AHM
spring.datasource.username=sa
spring.datasource.password=4V7lOXaxgAi3i6mgJL7qBUSPM
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.hikari.data-source-properties.cachePrepStmts=true
#spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
#spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
#
#spring.datasource.hikari.maximum-pool-size=15
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.auto-commit=false
#spring.datasource.hikari.leak-detection-threshold=20000



spring.autoconfigure.exclude= \
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

#security
security.oauth2.resource.filter-order=3
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true


# Log file location
logging.file.name=logs/transaction.log
# Log level for your application (default is INFO)
logging.level.root=INFO
# The filename pattern used to create log archives.
logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM}/transaction.%d{yyyy-MM-dd}.%i.log
# The maximum size of a log file before it is archived.
logging.logback.rollingpolicy.max-file-size=100MB
# The maximum size of all archived log files before older ones are deleted.
logging.logback.rollingpolicy.total-size-cap=10GB
# The maximum number of archive log files to keep.
logging.logback.rollingpolicy.max-history=10

management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.metrics.export.prometheus.enabled=true