#remote
server.port=8789
server.servlet.context-path=/classicwms/api/wms-inboundtransaction-service

#security
security.oauth2.resource.filter-order=3
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true

#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=false
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.hikari.maximum-pool-size=30
#spring.datasource.hikari.minimum-idle=10
#spring.datasource.hikari.idle-timeout=120000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000
#
##security
#security.oauth2.resource.filter-order=3
#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.jpa.properties.hibernate.order_updates=true


# Log file location
logging.file.name=logs/transaction.log
# Log level for your application (default is INFO)
logging.level.root=INFO
# The filename pattern used to create log archives.
logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM}/transaction.%d{yyyy-MM-dd}.%i.log
# The maximum size of a log file before it is archived.
logging.logback.rollingpolicy.max-file-size=100MB
# The maximum size of all archived log files before older ones are deleted.
logging.logback.rollingpolicy.total-size-cap=10GB
# The maximum number of archive log files to keep.
logging.logback.rollingpolicy.max-history=10

management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.metrics.export.prometheus.enabled=true