package com.tekclover.wms.api.outbound.transaction.model.report;

import lombok.Data;

import java.util.Date;

@Data
public class ContainerReceiptOutboundLine {

    private String languageId;
    private String companyCodeId;
    private String plantId;
    private String warehouseId;
    private String preInboundNo;
    private String refDocNumber;
    private String containerReceiptNo;
    private Date containerReceivedDate;
    private String containerNo;
    private Long statusId;
    private String containerType;
    private String partnerCode;
    private String invoiceNo;
    private String consignmentType;
    private String origin;
    private String numberOfPallets;
    private String numberOfCases;
    private String dockAllocationNo;
    private String remarks;
    private Long deletionIndicator;
    private String referenceField1;
    private String referenceField2;
    private String referenceField3;
    private String referenceField4;
    private String referenceField5;
    private String referenceField6;
    private String referenceField7;
    private String referenceField8;
    private String referenceField9;
    private String referenceField10;
    private Date referenceField11;
    private Date referenceField12;
    private Date referenceField13;
    private Date referenceField14;
    private Date referenceField15;
    private Date referenceField16;
    private Date referenceField17;
    private Date referenceField18;
    private Date referenceField19;
    private Date referenceField20;
    private String createdBy;
    private Date createdOn = new Date();
    private String updatedBy;
    private Date updatedOn = new Date();
    private String companyDescription;
    private String plantDescription;
    private String warehouseDescription;
    private String statusDescription;
    private String purchaseOrderNumber;
    private String middlewareId;
    private String middlewareTable;


    private String preOutboundNo;
    private Long lineNumber;
    private String itemCode;
    private String barcodeId;
    private String deliveryOrderNo;
    private String batchSerialNumber;
    private Long variantCode;
    private String variantSubCode;
    private Long outboundOrderTypeId;
    private Long stockTypeId;
    private Long specialStockIndicatorId;
    private String description;
    private Double orderQty;
    private String orderUom;
    private Double deliveryQty;
    private String deliveryUom;
    private String deliveryConfirmedBy;
    private Date deliveryConfirmedOn;
    private String reversedBy;
    private Date reversedOn;
    private String driverName;
    private String vehicleNO;
    private String itemText;
    private String mfrPartNumber;
    private String manufacturerName;
    private String storageSectionId;
    private Long middlewareHeaderId;
    private String referenceDocumentType;
    private String supplierInvoiceNo;
    private String salesOrderNumber;
    private String manufacturerFullName;
    private String salesInvoiceNumber;
    private String pickListNumber;
    private String tokenNumber;
    private Date invoiceDate;
    private String deliveryType;
    private String customerId;
    private String customerName;
    private String address;
    private String phoneNumber;
    private String alternateNo;
    private String status;
    private String transferOrderNo;
    private String returnOrderNo;
    private String isCompleted;
    private String isCancelled;
    private String targetBranchCode;
    private String customerType;
    private String handlingEquipment;
    private String assignedPickerId;
    private String materialNo;
    private String priceSegment;
    private String articleNo;
    private String gender;
    private String color;
    private String size;
    private String noPairs;
    private String tracking;
    private String alternateUom;
    private Double noBags;
    private Double bagSize;
    private Double mrp;
    private String itemType;
    private String itemGroup;
    private String brand;
    private Integer imsSaleTypeCode;
    private Double qtyInCase;
    private Double qtyInPiece;
    private Double qtyInCrate;
    private String deliveredPercentage;
    private String obReferenceField1;
    private String obReferenceField2;
    private String obReferenceField3;
    private String obReferenceField4;
    private String obReferenceField5;
    private String obReferenceField6;
    private String obReferenceField7;
    private String obReferenceField8;
    private String obReferenceField9;
    private String obReferenceField10;
    private Double pickConfirmQty;
    private Double inventoryQty;
    private Double allocatedQty;
    private String pickStBin;
    private Double uomQty;
    private String referenceField21;
    private String referenceField22;
    private String referenceField23;
    private String referenceField24;
    private String referenceField25;
    private String referenceField26;
    private String referenceField27;
    private String referenceField28;
    private String referenceField29;
    private String referenceField30;
    private String inventoryOwner;

    private String netWeight;
    private String grossWeight;

    private Date manufacturerDate;
    private Date expiryDate;
}
