server.port=8786

server.servlet.context-path=/classicwms

#UAT
spring.datasource.url=jdbc:sqlserver://10.10.6.30;databaseName=WMS_WK
spring.datasource.username=sa
spring.datasource.password=SuHcHQR72nxvyJx6EPpoOsK4V
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

#-----------Batch Configurtion-------------------------------------
spring.batch.initialize-schema=always
spring.batch.job.enabled=false
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

#security
security.oauth2.resource.filter-order=3

#---------------------------AsiaTime------------------------------

#spring.jackson.time-zone=UTC
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS
spring.jackson.time-zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata



# Log file location
logging.file.name=logs/wrapper.log
# Log level for your application (default is INFO)
logging.level.root=INFO
# The filename pattern used to create log archives.
logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM}/wrapper.%d{yyyy-MM-dd}.%i.log
# The maximum size of a log file before it is archived.
logging.logback.rollingpolicy.max-file-size=100MB
# The maximum size of all archived log files before older ones are deleted.
logging.logback.rollingpolicy.total-size-cap=10GB
# The maximum number of archive log files to keep.
logging.logback.rollingpolicy.max-history=10

management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.metrics.export.prometheus.enabled=true

